import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ShieldCheck, Zap, Wallet } from 'lucide-react';
import StatsCard from '@/components/StatsCard';
import MarketTable from '@/components/MarketTable';
import { getMarkets } from '@/lib/data';

export default async function HomePage() {
  const coins = await getMarkets();
  return <main><section className="relative overflow-hidden px-6 py-20"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_right,rgba(246,195,67,.2),transparent_35%),radial-gradient(circle_at_20%_20%,rgba(0,192,118,.12),transparent_30%)]"/><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="mb-4 inline-flex rounded-full border border-krypt-gold/30 bg-krypt-gold/10 px-4 py-2 text-sm text-krypt-gold">Next-generation crypto exchange UI</p><h1 className="text-5xl font-black leading-tight md:text-7xl">Trade crypto, futures and assets on <span className="text-krypt-gold">KryptSect</span></h1><p className="mt-6 max-w-2xl text-lg text-gray-400">A Binance-inspired trading platform with live markets, wallet connection, order books, futures interface, assets dashboard and polished exchange experience.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/trade" className="inline-flex items-center gap-2 rounded-xl bg-krypt-gold px-6 py-3 font-black text-black">Start Trading <ArrowRight size={18}/></Link><Link href="/markets" className="rounded-xl border border-white/10 px-6 py-3 font-bold hover:bg-white/10">Explore Markets</Link></div></div><div className="glass rounded-[2rem] p-4 shadow-glow"><Image src="/images/hero-dashboard.svg" alt="KryptSect trading dashboard" width={720} height={520} priority /></div></div></section><section className="mx-auto grid max-w-7xl gap-4 px-6 py-8 md:grid-cols-4"><StatsCard label="24h Volume" value="$82.4B" change="+12.4%"/><StatsCard label="Listed Markets" value="350+"/><StatsCard label="Supported Chains" value="6"/><StatsCard label="Fees From" value="0.10%"/></section><section className="mx-auto max-w-7xl px-6 py-12"><div className="mb-6 flex items-center justify-between"><h2 className="text-3xl font-black">Top Markets</h2><Link href="/markets" className="text-krypt-gold">View all</Link></div><MarketTable coins={coins.slice(0, 8)} /></section><section className="mx-auto grid max-w-7xl gap-4 px-6 py-12 md:grid-cols-3">{[{icon:ShieldCheck,title:'Secure wallet access',text:'Connect with RainbowKit and trade across major EVM chains.'},{icon:Zap,title:'Live market data',text:'Market prices load from CoinGecko with offline fallback data.'},{icon:Wallet,title:'Asset center',text:'Track spot, futures, earn and portfolio balances in one dashboard.'}].map(({icon:Icon,title,text}) => <div className="glass rounded-2xl p-6" key={title}><Icon className="text-krypt-gold"/><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-2 text-gray-400">{text}</p></div>)}</section></main>;
}
